// Travelpayouts affiliate link helpers.
//
// We earn commission only on clicks that carry our `marker` (the TP
// account ID). The marker lives in TRAVELPAYOUTS_MARKER and falls back
// to the literal 716767 so a missing env never silently drops attribution.
//
// Two surfaces:
//   - aviasalesUrl(): direct Aviasales search URL with marker — TP's
//     primary flight partner. This is the only flight link we currently
//     earn commission on; Skyscanner/Kayak/Expedia each need their own
//     separate affiliate programs.
//   - wrapTP(): generic redirector via tp.media/r for any other URL.
//     TP attributes if the destination matches a TP-partner domain
//     (Booking.com, Hotellook, etc.) and ignores it otherwise.

const MARKER = process.env.TRAVELPAYOUTS_MARKER ?? "716767";

function withMarker(marker: string, subId?: string): string {
  if (!subId) return marker;
  const safe = subId.replace(/[^a-zA-Z0-9._-]/g, "_").slice(0, 64);
  return `${marker}.${safe}`;
}

// Direct Aviasales search URL. Aviasales accepts ISO dates as
// `depart_date` / `return_date` and IATA codes as `origin_iata` /
// `destination_iata`. This is the canonical TP-attributed flight link.
export function aviasalesUrl(
  fromIata: string,
  toIata: string,
  isoStart?: string | null,
  isoEnd?: string | null,
  subId?: string,
): string {
  const params = new URLSearchParams({
    origin_iata: fromIata.toUpperCase(),
    destination_iata: toIata.toUpperCase(),
    adults: "1",
    marker: withMarker(MARKER, subId),
  });
  if (isoStart) params.set("depart_date", isoStart);
  if (isoEnd) params.set("return_date", isoEnd);
  return `https://www.aviasales.com/search?${params.toString()}`;
}

// WARNING: tp.media/r REQUIRES a per-partner `p=<id>` parameter. Without
// it, the endpoint returns 400. Since we don't have the partner ID map
// for every TP brand, prefer the per-partner short links generated in
// the TP dashboard (see *_SHORT_URL constants below). Keeping this
// helper around for future use but DO NOT call it without a known p.
export function wrapTP(rawUrl: string, subId: string, partnerId: string): string {
  if (!rawUrl || !partnerId) return rawUrl;
  const marker = withMarker(MARKER, subId);
  const params = new URLSearchParams({
    p: partnerId,
    marker,
    u: rawUrl,
  });
  return `https://tp.media/r?${params.toString()}`;
}

// ── Partner-specific short links ─────────────────────────────────────
// Each TP "Drive" link is a permanent, marker-tagged short URL that
// redirects to the partner with our marker baked in. We can append
// sub_id to any of them and TP forwards it to the partner for
// conversion-level tracking.
//
// Generated by the account holder in the TP dashboard; pasted in by
// nejihyuga1600 on 2026-06-17. If a partnership ends or the link
// rotates, regenerate the short link and update the constant here.

const AIRALO_SHORT_URL          = "https://airalo.tpk.ro/tK7Jd7dY";
const KIWITAXI_SHORT_URL        = "https://kiwitaxi.tpk.ro/yjha1RqW";
const GETRENTACAR_SHORT_URL     = "https://getrentacar.tpk.ro/TYu2XaKI";
const ECONOMYBOOKINGS_SHORT_URL = "https://economybookings.tpk.ro/obLadsCO";
const BIKESBOOKING_SHORT_URL    = "https://bikesbooking.tpk.ro/3khO6pbw";

function tagShortLink(shortUrl: string, subId?: string): string {
  if (!subId) return shortUrl;
  const safe = subId.replace(/[^a-zA-Z0-9._-]/g, "_").slice(0, 64);
  const sep = shortUrl.includes("?") ? "&" : "?";
  return `${shortUrl}${sep}sub_id=${safe}&clickref=${safe}`;
}

export const airaloUrl          = (subId?: string) => tagShortLink(AIRALO_SHORT_URL, subId);
export const kiwitaxiUrl        = (subId?: string) => tagShortLink(KIWITAXI_SHORT_URL, subId);
export const getrentacarUrl     = (subId?: string) => tagShortLink(GETRENTACAR_SHORT_URL, subId);
export const economybookingsUrl = (subId?: string) => tagShortLink(ECONOMYBOOKINGS_SHORT_URL, subId);
export const bikesbookingUrl    = (subId?: string) => tagShortLink(BIKESBOOKING_SHORT_URL, subId);

export const TP_MARKER = MARKER;
