// Shared airport lookup — used by style page and book page

export const AIRPORTS: Record<string, { name: string; iata: string }> = {
  // ── United States ──────────────────────────────────────────────────────────
  'New York':        { name: 'John F. Kennedy International',            iata: 'JFK' },
  'Los Angeles':     { name: 'Los Angeles International',                iata: 'LAX' },
  'Chicago':         { name: "O'Hare International",                     iata: 'ORD' },
  'Miami':           { name: 'Miami International',                      iata: 'MIA' },
  'Las Vegas':       { name: 'Harry Reid International',                 iata: 'LAS' },
  'San Francisco':   { name: 'San Francisco International',              iata: 'SFO' },
  'Seattle':         { name: 'Seattle-Tacoma International',             iata: 'SEA' },
  'Boston':          { name: 'Logan International',                      iata: 'BOS' },
  'Washington DC':   { name: 'Dulles International',                     iata: 'IAD' },
  'New Orleans':     { name: 'Louis Armstrong New Orleans International', iata: 'MSY' },
  'Nashville':       { name: 'Nashville International',                  iata: 'BNA' },
  'Denver':          { name: 'Denver International',                     iata: 'DEN' },
  'Austin':          { name: 'Austin-Bergstrom International',           iata: 'AUS' },
  'Phoenix':         { name: 'Phoenix Sky Harbor International',         iata: 'PHX' },
  'Honolulu':        { name: 'Daniel K. Inouye International',           iata: 'HNL' },
  'Atlanta':         { name: 'Hartsfield-Jackson Atlanta International', iata: 'ATL' },
  'Dallas':          { name: 'Dallas/Fort Worth International',          iata: 'DFW' },
  'Houston':         { name: 'George Bush Intercontinental',             iata: 'IAH' },
  'San Diego':       { name: 'San Diego International',                  iata: 'SAN' },
  'Portland':        { name: 'Portland International',                   iata: 'PDX' },
  'Minneapolis':     { name: 'Minneapolis\u2013Saint Paul International',iata: 'MSP' },
  'Detroit':         { name: 'Detroit Metropolitan',                     iata: 'DTW' },
  'Philadelphia':    { name: 'Philadelphia International',               iata: 'PHL' },
  'Baltimore':       { name: 'Baltimore/Washington International',       iata: 'BWI' },
  'Charlotte':       { name: 'Charlotte Douglas International',          iata: 'CLT' },
  'Tampa':           { name: 'Tampa International',                      iata: 'TPA' },
  'Orlando':         { name: 'Orlando International',                    iata: 'MCO' },
  'Sacramento':      { name: 'Sacramento International',                 iata: 'SMF' },
  'Salt Lake City':  { name: 'Salt Lake City International',             iata: 'SLC' },
  'Kansas City':     { name: 'Kansas City International',                iata: 'MCI' },
  'St. Louis':       { name: 'St. Louis Lambert International',          iata: 'STL' },
  'Indianapolis':    { name: 'Indianapolis International',               iata: 'IND' },
  'Columbus':        { name: 'John Glenn Columbus International',        iata: 'CMH' },
  'Cleveland':       { name: 'Cleveland Hopkins International',          iata: 'CLE' },
  'Pittsburgh':      { name: 'Pittsburgh International',                 iata: 'PIT' },
  'Albuquerque':     { name: 'Albuquerque International Sunport',        iata: 'ABQ' },
  'Tucson':          { name: 'Tucson International Airport',             iata: 'TUS' },
  'Reno':            { name: 'Reno-Tahoe International Airport',         iata: 'RNO' },
  'Boise':           { name: 'Boise Airport',                            iata: 'BOI' },
  'Anchorage':       { name: 'Ted Stevens Anchorage International',      iata: 'ANC' },
  'San Antonio':     { name: 'San Antonio International Airport',        iata: 'SAT' },
  'Oklahoma City':   { name: 'Will Rogers World Airport',                iata: 'OKC' },
  'Tulsa':           { name: 'Tulsa International Airport',              iata: 'TUL' },
  'Memphis':         { name: 'Memphis International Airport',            iata: 'MEM' },
  'Louisville':      { name: 'Louisville Muhammad Ali International',    iata: 'SDF' },
  'Raleigh':         { name: 'Raleigh-Durham International Airport',     iata: 'RDU' },
  'Raleigh-Durham':  { name: 'Raleigh-Durham International Airport',     iata: 'RDU' },
  'Richmond':        { name: 'Richmond International Airport',           iata: 'RIC' },
  'Norfolk':         { name: 'Norfolk International Airport',            iata: 'ORF' },
  'Jacksonville':    { name: 'Jacksonville International Airport',       iata: 'JAX' },
  'Fort Lauderdale': { name: 'Fort Lauderdale-Hollywood International',  iata: 'FLL' },
  'West Palm Beach': { name: 'Palm Beach International Airport',         iata: 'PBI' },
  'Fort Myers':      { name: 'Southwest Florida International Airport',  iata: 'RSW' },
  'Birmingham':      { name: 'Birmingham-Shuttlesworth International',   iata: 'BHM' },
  'Knoxville':       { name: 'McGhee Tyson Airport',                     iata: 'TYS' },
  'Chattanooga':     { name: 'Chattanooga Metropolitan Airport',         iata: 'CHA' },
  'Des Moines':      { name: 'Des Moines International Airport',         iata: 'DSM' },
  'Omaha':           { name: 'Eppley Airfield',                          iata: 'OMA' },
  'Wichita':         { name: 'Wichita Dwight D. Eisenhower National',    iata: 'ICT' },
  'El Paso':         { name: 'El Paso International Airport',            iata: 'ELP' },
  'Colorado Springs':{ name: 'Colorado Springs Airport',                 iata: 'COS' },
  'Grand Rapids':    { name: 'Gerald R. Ford International Airport',     iata: 'GRR' },
  'Dayton':          { name: 'Dayton International Airport',             iata: 'DAY' },
  'Akron':           { name: 'Akron-Canton Airport',                     iata: 'CAK' },
  'Lexington':       { name: 'Blue Grass Airport',                       iata: 'LEX' },
  'Spokane':         { name: 'Spokane International Airport',            iata: 'GEG' },
  'Little Rock':     { name: 'Bill and Hillary Clinton National Airport', iata: 'LIT' },
  'Madison':         { name: 'Dane County Regional Airport',             iata: 'MSN' },
  'Buffalo':         { name: 'Buffalo Niagara International Airport',    iata: 'BUF' },
  'Albany':          { name: 'Albany International Airport',             iata: 'ALB' },
  'Hartford':        { name: 'Bradley International Airport',            iata: 'BDL' },
  'Providence':      { name: 'T.F. Green Providence Airport',            iata: 'PVD' },
  'Savannah':        { name: 'Savannah/Hilton Head International',       iata: 'SAV' },
  'Greenville':      { name: 'Greenville-Spartanburg International',     iata: 'GSP' },
  'Fayetteville':    { name: 'Northwest Arkansas National Airport',      iata: 'XNA' },
  'Billings':        { name: 'Billings Logan International Airport',     iata: 'BIL' },
  'Sioux Falls':     { name: 'Sioux Falls Regional Airport',             iata: 'FSD' },
  'Lubbock':         { name: 'Lubbock Preston Smith International',      iata: 'LBB' },
  'Amarillo':        { name: 'Rick Husband Amarillo International',      iata: 'AMA' },
  'Corpus Christi':  { name: 'Corpus Christi International Airport',     iata: 'CRP' },
  'Midland':         { name: 'Midland International Air and Space Port',  iata: 'MAF' },
  'Pensacola':       { name: 'Pensacola International Airport',          iata: 'PNS' },
  'Jackson':         { name: 'Jackson-Medgar Wiley Evers International', iata: 'JAN' },
  'Springfield':     { name: 'Springfield-Branson National Airport',     iata: 'SGF' },
  // ── Canada ─────────────────────────────────────────────────────────────────
  'Toronto':         { name: 'Toronto Pearson International',            iata: 'YYZ' },
  'Vancouver':       { name: 'Vancouver International',                  iata: 'YVR' },
  'Montreal':        { name: 'Montr\u00e9al\u2013Trudeau International', iata: 'YUL' },
  'Calgary':         { name: 'Calgary International',                    iata: 'YYC' },
  'Ottawa':          { name: 'Ottawa Macdonald\u2013Cartier International', iata: 'YOW' },
  'Edmonton':        { name: 'Edmonton International',                   iata: 'YEG' },
  'Quebec City':     { name: 'Quebec City Jean Lesage International',    iata: 'YQB' },
  // ── Latin America ───────────────────────────────────────────────────────────
  'Mexico City':     { name: 'Benito Ju\u00e1rez International',         iata: 'MEX' },
  'Cancun':          { name: 'Canc\u00fan International',                iata: 'CUN' },
  'Havana':          { name: 'Jos\u00e9 Mart\u00ed International',       iata: 'HAV' },
  'San Juan':        { name: 'Luis Mu\u00f1oz Mar\u00edn International', iata: 'SJU' },
  'Bogota':          { name: 'El Dorado International',                  iata: 'BOG' },
  'Lima':            { name: 'Jorge Ch\u00e1vez International',          iata: 'LIM' },
  'Buenos Aires':    { name: 'Ministro Pistarini International',         iata: 'EZE' },
  'Rio de Janeiro':  { name: 'Gale\u00e3o International',               iata: 'GIG' },
  'Sao Paulo':       { name: 'S\u00e3o Paulo/Guarulhos International',   iata: 'GRU' },
  'Santiago':        { name: 'Arturo Merino Ben\u00edtez International', iata: 'SCL' },
  'Medellin':        { name: 'Jos\u00e9 Mar\u00eda C\u00f3rdova International', iata: 'MDE' },
  'Cartagena':       { name: 'Rafael N\u00fa\u00f1ez International',     iata: 'CTG' },
  'Quito':           { name: 'Mariscal Sucre International',             iata: 'UIO' },
  'Panama City':     { name: 'Tocumen International',                    iata: 'PTY' },
  'San Jose':        { name: 'Juan Santamar\u00eda International',       iata: 'SJO' },
  // ── Europe ─────────────────────────────────────────────────────────────────
  'London':          { name: 'Heathrow Airport',                         iata: 'LHR' },
  'Paris':           { name: 'Charles de Gaulle Airport',                iata: 'CDG' },
  'Amsterdam':       { name: 'Amsterdam Airport Schiphol',               iata: 'AMS' },
  'Frankfurt':       { name: 'Frankfurt Airport',                        iata: 'FRA' },
  'Munich':          { name: 'Munich Airport',                           iata: 'MUC' },
  'Berlin':          { name: 'Berlin Brandenburg Airport',               iata: 'BER' },
  'Madrid':          { name: 'Adolfo Su\u00e1rez Madrid\u2013Barajas Airport', iata: 'MAD' },
  'Barcelona':       { name: 'Josep Tarradellas Barcelona\u2013El Prat', iata: 'BCN' },
  'Rome':            { name: 'Leonardo da Vinci International',          iata: 'FCO' },
  'Milan':           { name: 'Milan Malpensa Airport',                   iata: 'MXP' },
  'Venice':          { name: 'Venice Marco Polo Airport',                iata: 'VCE' },
  'Florence':        { name: 'Florence Airport',                         iata: 'FLR' },
  'Naples':          { name: 'Naples International Airport',             iata: 'NAP' },
  'Zurich':          { name: 'Zurich Airport',                           iata: 'ZRH' },
  'Geneva':          { name: 'Geneva Airport',                           iata: 'GVA' },
  'Vienna':          { name: 'Vienna International Airport',             iata: 'VIE' },
  'Brussels':        { name: 'Brussels Airport',                         iata: 'BRU' },
  'Copenhagen':      { name: 'Copenhagen Airport',                       iata: 'CPH' },
  'Stockholm':       { name: 'Stockholm Arlanda Airport',                iata: 'ARN' },
  'Oslo':            { name: 'Oslo Airport Gardermoen',                  iata: 'OSL' },
  'Helsinki':        { name: 'Helsinki Airport',                         iata: 'HEL' },
  'Athens':          { name: 'Athens International Airport',             iata: 'ATH' },
  'Santorini':       { name: 'Santorini Airport',                        iata: 'JTR' },
  'Lisbon':          { name: 'Humberto Delgado Airport',                 iata: 'LIS' },
  'Porto':           { name: 'Francisco S\u00e1 Carneiro Airport',       iata: 'OPO' },
  'Dublin':          { name: 'Dublin Airport',                           iata: 'DUB' },
  'Edinburgh':       { name: 'Edinburgh Airport',                        iata: 'EDI' },
  'Nice':            { name: "Nice C\u00f4te d'Azur Airport",            iata: 'NCE' },
  'Prague':          { name: 'V\u00e1clav Havel Airport Prague',         iata: 'PRG' },
  'Budapest':        { name: 'Budapest Ferenc Liszt International',      iata: 'BUD' },
  'Warsaw':          { name: 'Warsaw Chopin Airport',                    iata: 'WAW' },
  'Krakow':          { name: 'Krak\u00f3w John Paul II International',   iata: 'KRK' },
  'Istanbul':        { name: 'Istanbul Airport',                         iata: 'IST' },
  'Moscow':          { name: 'Sheremetyevo International Airport',       iata: 'SVO' },
  'Dubrovnik':       { name: 'Dubrovnik Airport',                        iata: 'DBV' },
  'Split':           { name: 'Split Airport',                            iata: 'SPU' },
  'Reykjavik':       { name: 'Keflavik International Airport',           iata: 'KEF' },
  'Tallinn':         { name: 'Tallinn Airport',                          iata: 'TLL' },
  'Riga':            { name: 'Riga International Airport',               iata: 'RIX' },
  'Vilnius':         { name: 'Vilnius Airport',                          iata: 'VNO' },
  'Belgrade':        { name: 'Belgrade Nikola Tesla Airport',            iata: 'BEG' },
  'Bucharest':       { name: 'Henri Coan\u0103 International Airport',   iata: 'OTP' },
  'Sofia':           { name: 'Sofia Airport',                            iata: 'SOF' },
  'Tbilisi':         { name: 'Tbilisi International Airport',            iata: 'TBS' },
  'Yerevan':         { name: 'Zvartnots International Airport',          iata: 'EVN' },
  'Baku':            { name: 'Heydar Aliyev International Airport',      iata: 'GYD' },
  'Kyiv':            { name: 'Boryspil International Airport',           iata: 'KBP' },
  // ── Middle East ─────────────────────────────────────────────────────────────
  'Dubai':           { name: 'Dubai International Airport',              iata: 'DXB' },
  'Abu Dhabi':       { name: 'Abu Dhabi International Airport',          iata: 'AUH' },
  'Doha':            { name: 'Hamad International Airport',              iata: 'DOH' },
  'Tel Aviv':        { name: 'Ben Gurion International Airport',         iata: 'TLV' },
  'Amman':           { name: 'Queen Alia International Airport',         iata: 'AMM' },
  'Riyadh':          { name: 'King Khalid International Airport',        iata: 'RUH' },
  'Muscat':          { name: 'Muscat International Airport',             iata: 'MCT' },
  'Kuwait City':     { name: 'Kuwait International Airport',             iata: 'KWI' },
  'Beirut':          { name: 'Rafic Hariri International Airport',       iata: 'BEY' },
  'Tehran':          { name: 'Imam Khomeini International Airport',      iata: 'IKA' },
  // ── Africa ──────────────────────────────────────────────────────────────────
  'Cairo':           { name: 'Cairo International Airport',              iata: 'CAI' },
  'Marrakech':       { name: 'Marrakech Menara Airport',                 iata: 'RAK' },
  'Casablanca':      { name: 'Mohammed V International Airport',         iata: 'CMN' },
  'Nairobi':         { name: 'Jomo Kenyatta International Airport',      iata: 'NBO' },
  'Cape Town':       { name: 'Cape Town International Airport',          iata: 'CPT' },
  'Johannesburg':    { name: 'O.R. Tambo International Airport',         iata: 'JNB' },
  'Lagos':           { name: 'Murtala Muhammed International Airport',   iata: 'LOS' },
  'Accra':           { name: 'Kotoka International Airport',             iata: 'ACC' },
  'Kigali':          { name: 'Kigali International Airport',             iata: 'KGL' },
  // ── South & Central Asia ────────────────────────────────────────────────────
  'Mumbai':          { name: 'Chhatrapati Shivaji Maharaj International', iata: 'BOM' },
  'Delhi':           { name: 'Indira Gandhi International Airport',      iata: 'DEL' },
  'Bangalore':       { name: 'Kempegowda International Airport',         iata: 'BLR' },
  'Chennai':         { name: 'Chennai International Airport',            iata: 'MAA' },
  'Goa':             { name: 'Goa International Airport',                iata: 'GOI' },
  'Jaipur':          { name: 'Jaipur International Airport',             iata: 'JAI' },
  'Kathmandu':       { name: 'Tribhuvan International Airport',          iata: 'KTM' },
  'Colombo':         { name: 'Bandaranaike International Airport',       iata: 'CMB' },
  'Maldives':        { name: 'Velana International Airport',             iata: 'MLE' },
  'Dhaka':           { name: 'Hazrat Shahjalal International Airport',   iata: 'DAC' },
  // ── East & Southeast Asia ────────────────────────────────────────────────────
  'Tokyo':           { name: 'Narita International Airport',             iata: 'NRT' },
  'Osaka':           { name: 'Kansai International Airport',             iata: 'KIX' },
  'Kyoto':           { name: 'Kansai International Airport',             iata: 'KIX' },
  'Sapporo':         { name: 'New Chitose Airport',                      iata: 'CTS' },
  'Hiroshima':       { name: 'Hiroshima Airport',                        iata: 'HIJ' },
  'Fukuoka':         { name: 'Fukuoka Airport',                          iata: 'FUK' },
  'Seoul':           { name: 'Incheon International Airport',            iata: 'ICN' },
  'Busan':           { name: 'Gimhae International Airport',             iata: 'PUS' },
  'Beijing':         { name: 'Beijing Capital International Airport',    iata: 'PEK' },
  'Shanghai':        { name: 'Shanghai Pudong International Airport',    iata: 'PVG' },
  'Hong Kong':       { name: 'Hong Kong International Airport',          iata: 'HKG' },
  'Guangzhou':       { name: 'Guangzhou Baiyun International Airport',   iata: 'CAN' },
  'Taipei':          { name: 'Taiwan Taoyuan International Airport',     iata: 'TPE' },
  'Singapore':       { name: 'Singapore Changi Airport',                 iata: 'SIN' },
  'Bangkok':         { name: 'Suvarnabhumi Airport',                     iata: 'BKK' },
  'Chiang Mai':      { name: 'Chiang Mai International Airport',         iata: 'CNX' },
  'Phuket':          { name: 'Phuket International Airport',             iata: 'HKT' },
  'Kuala Lumpur':    { name: 'Kuala Lumpur International Airport',       iata: 'KUL' },
  'Manila':          { name: 'Ninoy Aquino International Airport',       iata: 'MNL' },
  'Bali':            { name: 'Ngurah Rai International Airport',         iata: 'DPS' },
  'Jakarta':         { name: 'Soekarno\u2013Hatta International Airport',iata: 'CGK' },
  'Hanoi':           { name: 'Noi Bai International Airport',            iata: 'HAN' },
  'Ho Chi Minh':     { name: 'Tan Son Nhat International Airport',       iata: 'SGN' },
  'Phnom Penh':      { name: 'Phnom Penh International Airport',         iata: 'PNH' },
  'Siem Reap':       { name: 'Siem Reap International Airport',          iata: 'SAI' },
  'Yangon':          { name: 'Yangon International Airport',             iata: 'RGN' },
  // ── Oceania ─────────────────────────────────────────────────────────────────
  'Sydney':          { name: 'Sydney Kingsford Smith Airport',           iata: 'SYD' },
  'Melbourne':       { name: 'Melbourne Airport',                        iata: 'MEL' },
  'Brisbane':        { name: 'Brisbane Airport',                         iata: 'BNE' },
  'Perth':           { name: 'Perth Airport',                            iata: 'PER' },
  'Adelaide':        { name: 'Adelaide Airport',                         iata: 'ADL' },
  'Auckland':        { name: 'Auckland Airport',                         iata: 'AKL' },
  'Wellington':      { name: 'Wellington Airport',                       iata: 'WLG' },
  'Queenstown':      { name: 'Queenstown Airport',                       iata: 'ZQN' },
  'Fiji':            { name: 'Nadi International Airport',               iata: 'NAN' },
  // ── Additional regional / gateway airports ──────────────────────────────────
  'Shizuoka':        { name: 'Shizuoka Airport',                         iata: 'FSZ' },
  'Nagoya':          { name: 'Chubu Centrair International Airport',     iata: 'NGO' },
  'Naha':            { name: 'Naha Airport (Okinawa)',                   iata: 'OKA' },
  'Cusco':           { name: 'Alejandro Velasco Astete International',   iata: 'CUZ' },
  'Papeete':         { name: 'Fa\u0101\u2019a International Airport',   iata: 'PPT' },
  'Bora Bora':       { name: 'Bora Bora Airport',                        iata: 'BOB' },
  'Jackson Hole':    { name: 'Jackson Hole Airport',                     iata: 'JAC' },
  'Bergen':          { name: 'Bergen Airport Flesland',                  iata: 'BGO' },
  'Punta Arenas':    { name: 'Carlos Ib\u00e1\u00f1ez del Campo International', iata: 'PUQ' },
};

// ── Landmark → nearest commercial airport ──────────────────────────────────
// Maps popular non-city destinations to the nearest/most-used airport city key.
const LANDMARK_AIRPORTS: Record<string, string> = {
  // Japan
  'Mount Fuji':          'Shizuoka',   // FSZ ~50 km; or swap to 'Tokyo' for Narita/Haneda
  'Fuji':                'Shizuoka',
  'Hakone':              'Tokyo',
  'Nikko':               'Tokyo',
  'Nara':                'Osaka',
  'Hiroshima Peace Memorial': 'Hiroshima',
  // USA
  'Grand Canyon':        'Las Vegas',
  'Yellowstone':         'Jackson Hole',
  'Niagara Falls':       'Buffalo',
  'Yosemite':            'San Francisco',
  'Zion':                'Las Vegas',
  'Bryce Canyon':        'Las Vegas',
  'Arches':              'Salt Lake City',
  'Monument Valley':     'Phoenix',
  // South America
  'Machu Picchu':        'Cusco',
  'Iguazu Falls':        'Buenos Aires',
  'Patagonia':           'Punta Arenas',
  'Torres del Paine':    'Punta Arenas',
  'Galapagos':           'Quito',
  // Asia
  'Angkor Wat':          'Siem Reap',
  'Mount Everest':       'Kathmandu',
  'Everest Base Camp':   'Kathmandu',
  'Taj Mahal':           'Delhi',
  'Agra':                'Delhi',
  'Varanasi':            'Delhi',
  'Halong Bay':          'Hanoi',
  'Bagan':               'Yangon',
  // Pacific
  'Bora Bora':           'Bora Bora',
  'Tahiti':              'Papeete',
  // Africa
  'Masai Mara':          'Nairobi',
  'Serengeti':           'Nairobi',
  'Sahara':              'Marrakech',
  'Victoria Falls':      'Johannesburg',
  'Kilimanjaro':         'Nairobi',
  // Europe
  'Santorini':           'Santorini',
  'Amalfi Coast':        'Naples',
  'Cinque Terre':        'Florence',
  'Swiss Alps':          'Zurich',
  'Lofoten':             'Bergen',
  'Fjords':              'Bergen',
  'Norwegian Fjords':    'Bergen',
};

export function findAirport(loc: string): { name: string; iata: string; city: string } | null {
  if (!loc) return null;
  const lower = loc.toLowerCase().trim();

  // 1. Exact match
  for (const [key, val] of Object.entries(AIRPORTS)) {
    if (key.toLowerCase() === lower) return { ...val, city: key };
  }

  // 2. Substring / partial match
  for (const [key, val] of Object.entries(AIRPORTS)) {
    const k = key.toLowerCase();
    if (lower.includes(k) || k.includes(lower.split(',')[0].trim())) return { ...val, city: key };
  }

  // 3. Landmark alias map — nearest commercial airport for non-city destinations
  for (const [landmark, cityKey] of Object.entries(LANDMARK_AIRPORTS)) {
    if (lower.includes(landmark.toLowerCase()) || landmark.toLowerCase().includes(lower)) {
      const airport = AIRPORTS[cityKey];
      if (airport) return { ...airport, city: cityKey };
    }
  }

  return null;
}

export function airportLabel(loc: string): string {
  const found = findAirport(loc);
  return found ? `${found.name} (${found.iata})` : loc;
}

export function extractIata(val: string): string {
  return val.match(/\(([A-Z]{3})\)/)?.[1] ?? findAirport(val)?.iata ?? val;
}
