// Static travel cheat-sheet for the live-now page.
//
// One entry per ISO 3166-1 alpha-2 country code. Curated for the top ~35
// tourist destinations; every field is optional so partial data still
// renders. Kept in code (not JSON) so tree-shaking drops unused countries
// and the shape is type-checked at call sites.
//
// Exchange rates are approximate (Aug 2026 baseline) — good enough for a
// "5 EUR ≈ $5.40" sanity check on the ground, not for accounting. If we
// need live rates later, swap the number for a fetch to /api/fx.

export interface CountryFacts {
  name: string;
  currency: { code: string; symbol: string; usdRate: number };
  tipping: string;
  cashVsCard: string;
  waterSafe: boolean;
  plug: string;                 // 230V Type F, 120V Type A/B, etc.
  phrases: { hello: string; thanks: string; bathroom: string };
  cultureNote?: string;         // one short line
}

export const COUNTRY_CHEATSHEET: Record<string, CountryFacts> = {
  CZ: {
    name: 'Czech Republic',
    currency: { code: 'CZK', symbol: 'Kč', usdRate: 23.5 },
    tipping: '10% at sit-down restaurants; round up for taxis',
    cashVsCard: 'Card accepted almost everywhere; small pubs still cash-preferred',
    waterSafe: true,
    plug: '230V · Type E (round pins)',
    phrases: { hello: 'Ahoj', thanks: 'Děkuji', bathroom: 'Toaleta, prosím?' },
    cultureNote: "Don't clink beer bottles — only glasses. And never in silence: it's bad luck.",
  },
  FR: {
    name: 'France',
    currency: { code: 'EUR', symbol: '€', usdRate: 0.92 },
    tipping: 'Service compris — round up €1-2 for good service',
    cashVsCard: 'Card everywhere; keep €20 cash for bakeries + markets',
    waterSafe: true,
    plug: '230V · Type E',
    phrases: { hello: 'Bonjour', thanks: 'Merci', bathroom: 'Où sont les toilettes ?' },
    cultureNote: 'Always greet with "Bonjour" before asking a question — shops, buses, everywhere.',
  },
  IT: {
    name: 'Italy',
    currency: { code: 'EUR', symbol: '€', usdRate: 0.92 },
    tipping: 'Not expected; coperto (cover charge) already on the bill',
    cashVsCard: 'Card mainstream; small trattorias may be cash-only',
    waterSafe: true,
    plug: '230V · Type F/L',
    phrases: { hello: 'Ciao', thanks: 'Grazie', bathroom: 'Dov\'è il bagno?' },
    cultureNote: 'No cappuccino after 11 AM — locals switch to espresso.',
  },
  ES: {
    name: 'Spain',
    currency: { code: 'EUR', symbol: '€', usdRate: 0.92 },
    tipping: 'Rounding up is enough; €1-2 for full meals',
    cashVsCard: 'Card mostly; small bars cash',
    waterSafe: true,
    plug: '230V · Type F',
    phrases: { hello: 'Hola', thanks: 'Gracias', bathroom: '¿Dónde está el baño?' },
    cultureNote: 'Dinner starts 9-10 PM. Restaurants close 4-8 PM.',
  },
  DE: {
    name: 'Germany',
    currency: { code: 'EUR', symbol: '€', usdRate: 0.92 },
    tipping: '5-10%, tell the server the amount as you pay',
    cashVsCard: 'Cash is king outside major chains — always carry €50+',
    waterSafe: true,
    plug: '230V · Type F',
    phrases: { hello: 'Hallo', thanks: 'Danke', bathroom: 'Wo ist die Toilette?' },
    cultureNote: 'Cross the street on red = social sin. Wait for green.',
  },
  GB: {
    name: 'United Kingdom',
    currency: { code: 'GBP', symbol: '£', usdRate: 1.27 },
    tipping: '10-12.5% (often added as service charge)',
    cashVsCard: 'Contactless universal; cash almost never needed',
    waterSafe: true,
    plug: '230V · Type G (big rectangular pins)',
    phrases: { hello: 'Hello', thanks: 'Thanks', bathroom: 'Where\'s the loo?' },
    cultureNote: 'Queue religiously. Skipping is worse than swearing at the King.',
  },
  US: {
    name: 'United States',
    currency: { code: 'USD', symbol: '$', usdRate: 1 },
    tipping: '18-22% at sit-down restaurants; $1-2 per drink at bars',
    cashVsCard: 'Card everywhere; tips often added on the terminal',
    waterSafe: true,
    plug: '120V · Type A/B',
    phrases: { hello: 'Hi', thanks: 'Thanks', bathroom: 'Restroom?' },
    cultureNote: 'Tax + tip are added after — the menu price is not the final price.',
  },
  JP: {
    name: 'Japan',
    currency: { code: 'JPY', symbol: '¥', usdRate: 0.0067 },
    tipping: 'Do NOT tip — considered rude',
    cashVsCard: 'Cash still dominant outside chains; carry ¥10 000+',
    waterSafe: true,
    plug: '100V · Type A (US-compatible pins)',
    phrases: { hello: 'こんにちは (Konnichiwa)', thanks: 'ありがとう (Arigatō)', bathroom: 'トイレはどこですか？' },
    cultureNote: 'Bow slightly when greeting. Take shoes off before tatami.',
  },
  CN: {
    name: 'China',
    currency: { code: 'CNY', symbol: '¥', usdRate: 0.14 },
    tipping: 'Not expected anywhere',
    cashVsCard: 'WeChat/Alipay dominant; foreign cards often fail — bring cash',
    waterSafe: false,
    plug: '220V · Type A/I',
    phrases: { hello: '你好 (Nǐ hǎo)', thanks: '谢谢 (Xièxie)', bathroom: '洗手间在哪里?' },
    cultureNote: 'VPN needed for Google/WhatsApp/Instagram. Install before you land.',
  },
  TH: {
    name: 'Thailand',
    currency: { code: 'THB', symbol: '฿', usdRate: 0.028 },
    tipping: 'Round up or 10% at nice restaurants',
    cashVsCard: 'Cash for markets and tuk-tuks; card at hotels + malls',
    waterSafe: false,
    plug: '220V · Type A/B/C',
    phrases: { hello: 'Sawasdee', thanks: 'Khob khun', bathroom: 'Hongnam yoo tee nai?' },
    cultureNote: 'Never touch anyone\'s head — even a child\'s.',
  },
  MX: {
    name: 'Mexico',
    currency: { code: 'MXN', symbol: '$', usdRate: 0.058 },
    tipping: '10-15% at restaurants; small change for taxi/parking',
    cashVsCard: 'Card at hotels + big restaurants; cash for street food + markets',
    waterSafe: false,
    plug: '127V · Type A/B',
    phrases: { hello: 'Hola', thanks: 'Gracias', bathroom: '¿Dónde está el baño?' },
    cultureNote: 'Don\'t drink tap water — even for brushing teeth.',
  },
  BR: {
    name: 'Brazil',
    currency: { code: 'BRL', symbol: 'R$', usdRate: 0.20 },
    tipping: '10% often included as "taxa de serviço"; add a bit for extras',
    cashVsCard: 'Card + Pix universal; cash useful in small towns',
    waterSafe: false,
    plug: '127/220V · Type N',
    phrases: { hello: 'Olá', thanks: 'Obrigado', bathroom: 'Onde é o banheiro?' },
    cultureNote: 'Portuguese, not Spanish. Locals appreciate the difference.',
  },
  AR: {
    name: 'Argentina',
    currency: { code: 'ARS', symbol: '$', usdRate: 0.0011 },
    tipping: '10% at sit-down; taxi drivers not tipped',
    cashVsCard: 'Bring USD 100s — "blue" exchange gets 2× the official rate at cambios',
    waterSafe: true,
    plug: '220V · Type C/I',
    phrases: { hello: 'Hola', thanks: 'Gracias', bathroom: '¿Dónde está el baño?' },
    cultureNote: 'Dinner is late — 10 PM is normal.',
  },
  AU: {
    name: 'Australia',
    currency: { code: 'AUD', symbol: '$', usdRate: 0.65 },
    tipping: 'Not expected; rounding up appreciated',
    cashVsCard: 'Card everywhere; contactless standard',
    waterSafe: true,
    plug: '230V · Type I',
    phrases: { hello: 'G\'day', thanks: 'Thanks / Ta', bathroom: 'Where\'s the loo / dunny?' },
    cultureNote: 'Sun is brutal — SPF 50, hat, shirt even on cloudy days.',
  },
  NZ: {
    name: 'New Zealand',
    currency: { code: 'NZD', symbol: '$', usdRate: 0.60 },
    tipping: 'Not expected',
    cashVsCard: 'Contactless everywhere; some rural spots cash-only',
    waterSafe: true,
    plug: '230V · Type I',
    phrases: { hello: 'Kia ora', thanks: 'Cheers', bathroom: 'Where\'s the toilet?' },
    cultureNote: 'Māori greeting "Kia ora" works anywhere — even in shops.',
  },
  PT: {
    name: 'Portugal',
    currency: { code: 'EUR', symbol: '€', usdRate: 0.92 },
    tipping: 'Round up €1-2, or 10% for full meals',
    cashVsCard: 'Card widely accepted; MB Way (local) preferred for splits',
    waterSafe: true,
    plug: '230V · Type F',
    phrases: { hello: 'Olá', thanks: 'Obrigado', bathroom: 'Onde é a casa de banho?' },
  },
  NL: {
    name: 'Netherlands',
    currency: { code: 'EUR', symbol: '€', usdRate: 0.92 },
    tipping: '5-10% for meals; not expected for coffee',
    cashVsCard: 'PIN (Maestro) dominant — foreign Visa/Mastercard sometimes rejected',
    waterSafe: true,
    plug: '230V · Type F',
    phrases: { hello: 'Hallo', thanks: 'Dank je', bathroom: 'Waar is het toilet?' },
    cultureNote: 'Bikes have right-of-way. Look twice before crossing any bike lane.',
  },
  GR: {
    name: 'Greece',
    currency: { code: 'EUR', symbol: '€', usdRate: 0.92 },
    tipping: '5-10% at tavernas; round up otherwise',
    cashVsCard: 'Card at hotels; cash for tavernas + kiosks + islands',
    waterSafe: true,
    plug: '230V · Type F',
    phrases: { hello: 'Yasou', thanks: 'Efharistó', bathroom: 'Pou íne i toualéta?' },
  },
  TR: {
    name: 'Turkey',
    currency: { code: 'TRY', symbol: '₺', usdRate: 0.030 },
    tipping: '10% at restaurants; not for taxis',
    cashVsCard: 'Card widely OK; carry cash for bazaars',
    waterSafe: false,
    plug: '230V · Type F',
    phrases: { hello: 'Merhaba', thanks: 'Teşekkür ederim', bathroom: 'Tuvalet nerede?' },
  },
  AE: {
    name: 'United Arab Emirates',
    currency: { code: 'AED', symbol: 'د.إ', usdRate: 0.27 },
    tipping: '10-15% usually added; extra for great service',
    cashVsCard: 'Card universal',
    waterSafe: true,
    plug: '230V · Type G',
    phrases: { hello: 'Marhaba', thanks: 'Shukran', bathroom: 'Ayn al hammam?' },
    cultureNote: 'Modest dress (covered shoulders/knees) in malls and mosques. Fri = weekend.',
  },
  IN: {
    name: 'India',
    currency: { code: 'INR', symbol: '₹', usdRate: 0.012 },
    tipping: '10% at nicer restaurants; small change for porters',
    cashVsCard: 'UPI + card in cities; cash needed in small towns',
    waterSafe: false,
    plug: '230V · Type C/D/M',
    phrases: { hello: 'Namaste', thanks: 'Dhanyavaad', bathroom: 'Bathroom kahan hai?' },
    cultureNote: 'Right hand only for eating and giving. Take shoes off entering homes/temples.',
  },
  KR: {
    name: 'South Korea',
    currency: { code: 'KRW', symbol: '₩', usdRate: 0.00075 },
    tipping: 'Not expected — sometimes refused',
    cashVsCard: 'Card everywhere; T-money card for transit',
    waterSafe: true,
    plug: '220V · Type C/F',
    phrases: { hello: '안녕하세요 (Annyeonghaseyo)', thanks: '감사합니다 (Kamsahamnida)', bathroom: '화장실 어디예요?' },
  },
  VN: {
    name: 'Vietnam',
    currency: { code: 'VND', symbol: '₫', usdRate: 0.000040 },
    tipping: 'Not expected; round up for great service',
    cashVsCard: 'Cash for street food; card at hotels + malls',
    waterSafe: false,
    plug: '220V · Type A/C',
    phrases: { hello: 'Xin chào', thanks: 'Cảm ơn', bathroom: 'Nhà vệ sinh ở đâu?' },
  },
  ID: {
    name: 'Indonesia',
    currency: { code: 'IDR', symbol: 'Rp', usdRate: 0.000063 },
    tipping: '10% at nicer places; small change for drivers',
    cashVsCard: 'Cash for warungs + drivers; card at hotels',
    waterSafe: false,
    plug: '230V · Type C/F',
    phrases: { hello: 'Halo', thanks: 'Terima kasih', bathroom: 'Di mana kamar mandi?' },
  },
  CA: {
    name: 'Canada',
    currency: { code: 'CAD', symbol: '$', usdRate: 0.73 },
    tipping: '15-20% at restaurants',
    cashVsCard: 'Card everywhere; contactless standard',
    waterSafe: true,
    plug: '120V · Type A/B',
    phrases: { hello: 'Hi / Bonjour', thanks: 'Thanks / Merci', bathroom: 'Washroom?' },
  },
  IS: {
    name: 'Iceland',
    currency: { code: 'ISK', symbol: 'kr', usdRate: 0.0073 },
    tipping: 'Not expected',
    cashVsCard: 'Card for everything — even public restrooms',
    waterSafe: true,
    plug: '230V · Type F',
    phrases: { hello: 'Halló', thanks: 'Takk', bathroom: 'Hvar er klósettið?' },
    cultureNote: 'Tap water is glacier-fresh. Bottled water is a scam.',
  },
  CH: {
    name: 'Switzerland',
    currency: { code: 'CHF', symbol: 'CHF', usdRate: 1.14 },
    tipping: 'Not required — service is included',
    cashVsCard: 'Card everywhere; TWINT for local splits',
    waterSafe: true,
    plug: '230V · Type J',
    phrases: { hello: 'Grüezi', thanks: 'Merci', bathroom: 'Wo ist die Toilette?' },
  },
};

export function factsFor(countryCode: string | null): CountryFacts | null {
  if (!countryCode) return null;
  return COUNTRY_CHEATSHEET[countryCode.toUpperCase()] ?? null;
}
