'use client';
// Curated-for-you recommendations rail — sits inside the Planning tab.
// Horizontal snap-scroll of cards generated by /api/recommendations,
// personalised against the user's saved TripDraft.style preferences.
//
// Following the ui-ux-pro-max skill's "Horizontal Scroll Journey" pattern
// + motion-driven style guidance: 280px cards, 1px lavender hairline on
// hover/focus, scale-on-press, 150-300ms transitions.
//
// Accessibility:
//   - Touch targets >= 44px
//   - role="list" / "listitem" so screen readers can navigate
//   - Visible focus ring (2px lavender)
//   - prefers-reduced-motion respected via CSS-level @media
//   - color contrast: ink-on-glass-surface ≥4.5:1 in both light + dark

import { useEffect, useState, useCallback } from 'react';

interface Rec {
  id: string;
  name: string;
  category: 'restaurant' | 'sight' | 'experience' | 'off-beat' | 'neighborhood';
  blurb: string;
  whyItFits: string;
  duration?: string;
  priceTier?: 1 | 2 | 3;
}

interface Props {
  tripId: string;
  destination: string | null;
}

// Category → small color tag. Keeps cards visually distinguishable at a
// glance without resorting to emoji icons (ui-ux-pro-max rule: no emoji icons).
const CATEGORY_TINT: Record<Rec['category'], { fg: string; bg: string }> = {
  restaurant:   { fg: '#fbbf24', bg: 'rgba(251,191,36,0.12)' }, // saffron — food
  sight:        { fg: '#7dd3fc', bg: 'rgba(125,211,252,0.12)' },// icy blue — sights
  experience:   { fg: '#a78bfa', bg: 'rgba(167,139,250,0.14)' },// lavender — experiences
  'off-beat':   { fg: '#f87171', bg: 'rgba(248,113,113,0.10)' },// soft red — off-beat
  neighborhood: { fg: '#7cff97', bg: 'rgba(124,255,151,0.10)' },// success green — neighborhoods
};

export function RecommendationsRail({ tripId, destination }: Props) {
  const [recs, setRecs] = useState<Rec[] | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchRecs = useCallback(async () => {
    if (!tripId) return;
    setLoading(true);
    setError(null);
    try {
      const r = await fetch('/api/recommendations', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ tripId }),
      });
      if (!r.ok) {
        const j = await r.json().catch(() => null);
        throw new Error(j?.error ?? `HTTP ${r.status}`);
      }
      const j = await r.json() as { recommendations: Rec[] };
      setRecs(j.recommendations);
    } catch (e) {
      console.error('[recommendations] fetch failed', e);
      setError(e instanceof Error ? e.message : 'Failed to load recommendations');
    } finally {
      setLoading(false);
    }
  }, [tripId]);

  useEffect(() => {
    fetchRecs();
  }, [fetchRecs]);

  return (
    <section
      aria-label="Curated recommendations for your trip"
      style={{
        margin: '32px 0',
        padding: '0 16px',
      }}
    >
      <header style={{
        display: 'flex', alignItems: 'baseline', justifyContent: 'space-between',
        gap: 12, marginBottom: 14,
      }}>
        <div style={{ minWidth: 0 }}>
          <div style={{
            fontFamily: 'var(--font-mono-display), monospace',
            fontSize: 10, letterSpacing: '0.22em',
            color: 'var(--brand-accent)', textTransform: 'uppercase',
            marginBottom: 6, fontWeight: 700,
          }}>
            ✦ Curated for you
          </div>
          <h2 style={{
            margin: 0,
            fontFamily: 'var(--font-display, Georgia, serif)',
            fontSize: 'clamp(22px, 3vw, 30px)',
            fontWeight: 600, letterSpacing: '-0.015em',
            color: 'var(--brand-ink)',
          }}>
            {destination ? <>Picks for your {destination} trip</> : 'Picks for your trip'}
          </h2>
        </div>
        {recs && !loading && (
          <button
            onClick={fetchRecs}
            aria-label="Refresh recommendations"
            style={refreshBtnStyle}
          >
            ↻ Refresh
          </button>
        )}
      </header>

      {/* Loading state — skeleton cards matching the real card layout so
          we don't trigger CLS when the data lands. ui-ux-pro-max:
          progressive-loading rule. */}
      {loading && (
        <div style={railStyle}>
          {Array.from({ length: 4 }).map((_, i) => (
            <div key={i} aria-hidden style={skeletonCard} />
          ))}
        </div>
      )}

      {error && !loading && (
        <div style={{
          padding: '14px 16px', borderRadius: 12,
          background: 'rgba(248,113,113,0.10)',
          border: '1px solid rgba(248,113,113,0.30)',
          color: 'var(--brand-danger)',
          fontSize: 13,
        }}>
          Couldn&apos;t pull recommendations: {error}.{' '}
          <button onClick={fetchRecs} style={inlineLinkBtn}>Try again</button>.
        </div>
      )}

      {!loading && !error && recs && (
        <ul role="list" style={railStyle}>
          {recs.map(rec => (
            <li key={rec.id} role="listitem" style={{ listStyle: 'none' }}>
              <RecCard rec={rec} />
            </li>
          ))}
        </ul>
      )}

      {/* Scoped CSS — `:focus-visible` ring + prefers-reduced-motion guard.
          Inline <style> keeps the component self-contained without a
          dependency on Tailwind / styled-components. */}
      <style>{`
        .rec-card {
          transition: transform 200ms var(--ease-out, ease-out),
                      border-color 200ms ease,
                      box-shadow 200ms ease;
        }
        .rec-card:hover {
          transform: translateY(-2px) scale(1.01);
          border-color: rgba(167,139,250,0.40);
          box-shadow: 0 8px 24px rgba(167,139,250,0.18);
        }
        .rec-card:focus-visible {
          outline: 2px solid var(--brand-accent);
          outline-offset: 2px;
        }
        .rec-rail { scroll-snap-type: x mandatory; }
        .rec-card { scroll-snap-align: start; }
        @media (prefers-reduced-motion: reduce) {
          .rec-card { transition: none; }
          .rec-card:hover { transform: none; }
        }
      `}</style>
    </section>
  );
}

function RecCard({ rec }: { rec: Rec }) {
  const tint = CATEGORY_TINT[rec.category];
  const priceLabel = rec.priceTier ? '$'.repeat(rec.priceTier) : null;
  return (
    <article
      className="rec-card"
      tabIndex={0}
      style={{
        width: 280,
        minHeight: 220,
        padding: '18px 18px 16px',
        background: 'rgba(255,255,255,0.03)',
        border: '1px solid var(--brand-border)',
        borderRadius: 14,
        cursor: 'pointer',
        display: 'flex', flexDirection: 'column', gap: 10,
        backdropFilter: 'blur(8px)',
        WebkitBackdropFilter: 'blur(8px)',
      }}
    >
      <div style={{
        display: 'inline-flex', alignItems: 'center', gap: 8,
        alignSelf: 'flex-start',
      }}>
        <span style={{
          fontFamily: 'var(--font-mono-display), monospace',
          fontSize: 9, letterSpacing: '0.18em',
          padding: '3px 8px', borderRadius: 999,
          background: tint.bg,
          color: tint.fg,
          textTransform: 'uppercase', fontWeight: 700,
        }}>
          {rec.category === 'off-beat' ? 'Off-beat' : rec.category}
        </span>
        {priceLabel && (
          <span style={{
            fontFamily: 'var(--font-mono-display), monospace',
            fontSize: 10, letterSpacing: '0.10em',
            color: 'var(--brand-ink-mute)', fontWeight: 600,
          }}>
            {priceLabel}
          </span>
        )}
        {rec.duration && (
          <span style={{
            fontFamily: 'var(--font-mono-display), monospace',
            fontSize: 10, letterSpacing: '0.10em',
            color: 'var(--brand-ink-mute)',
          }}>
            · {rec.duration}
          </span>
        )}
      </div>

      <h3 style={{
        margin: 0,
        fontFamily: 'var(--font-display, Georgia, serif)',
        fontSize: 18, fontWeight: 600,
        letterSpacing: '-0.005em',
        color: 'var(--brand-ink)',
        lineHeight: 1.2,
      }}>
        {rec.name}
      </h3>

      <p style={{
        margin: 0,
        fontSize: 13, lineHeight: 1.5,
        color: 'var(--brand-ink-dim)',
        // Cap at 3 lines so card heights stay tidy in the rail.
        display: '-webkit-box', WebkitLineClamp: 3, WebkitBoxOrient: 'vertical',
        overflow: 'hidden',
      }}>
        {rec.blurb}
      </p>

      <p style={{
        margin: 'auto 0 0',
        fontSize: 12, lineHeight: 1.4,
        fontStyle: 'italic',
        color: tint.fg,
      }}>
        ✦ {rec.whyItFits}
      </p>
    </article>
  );
}

const railStyle: React.CSSProperties = {
  display: 'flex',
  gap: 14,
  overflowX: 'auto',
  padding: '4px 0 18px',
  margin: 0,
  scrollbarWidth: 'thin',
  WebkitOverflowScrolling: 'touch',
};

const skeletonCard: React.CSSProperties = {
  width: 280, minHeight: 220, flex: '0 0 auto',
  background: 'rgba(255,255,255,0.03)',
  border: '1px solid var(--brand-border)',
  borderRadius: 14,
  // Subtle pulse via CSS keyframe declared globally — we lean on a
  // simple opacity sweep rather than shimmer so we don't ship a heavy
  // gradient animation for a transient state.
  animation: 'pageFadeIn 1.6s ease-in-out infinite alternate',
};

const refreshBtnStyle: React.CSSProperties = {
  flexShrink: 0,
  padding: '6px 12px', borderRadius: 999,
  background: 'transparent',
  border: '1px solid var(--brand-border)',
  color: 'var(--brand-ink-dim)',
  fontFamily: 'var(--font-mono-display), monospace',
  fontSize: 11, fontWeight: 600,
  letterSpacing: '0.08em',
  cursor: 'pointer',
};

const inlineLinkBtn: React.CSSProperties = {
  background: 'none', border: 'none',
  color: 'var(--brand-accent)',
  fontFamily: 'inherit', fontSize: 13,
  textDecoration: 'underline',
  cursor: 'pointer', padding: 0,
};
