// POST /api/trips/add-from-share
//
// Called by the iOS Share Extension after the user picks which trip to add
// the shared location to. Appends a "Saved from share" line to the trip's
// markdown itinerary and pushes a source-URL comment so the trip screen can
// render a "shared from Instagram" chip later.
//
// Body:
//   { tripId: string | "new",
//     venueName: string,
//     city?: string, country?: string,
//     lat?: number, lon?: number,
//     dayIndex?: number,             // 1-based; append to day N. Omit → last day.
//     source: "instagram" | ...,     // for provenance
//     sourceUrl?: string,
//     thumbnail?: string }
//
// Returns { trip: TripDraft, tripUrl: string } so the extension can open
// the main app deep-linked to the trip.

import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { checkTripSaveLimit } from "@/lib/plan";
import { mapCategory } from "@/lib/places-categories";

type ShareBody = {
  tripId?: string;
  venueName?: string;
  city?: string;
  country?: string;
  lat?: number;
  lon?: number;
  dayIndex?: number;
  source?: string;
  sourceUrl?: string;
  thumbnail?: string;
  placeTypes?: string[];   // optional — from Places lookup during share-unfurl
};

export async function POST(req: Request) {
  const session = await auth();
  const userId = (session?.user as { id?: string })?.id;
  if (!userId) return Response.json({ error: "Unauthorized" }, { status: 401 });

  let body: ShareBody;
  try {
    body = await req.json();
  } catch {
    return Response.json({ error: "Invalid JSON" }, { status: 400 });
  }
  const venue = (body.venueName ?? "").trim();
  if (!venue) return Response.json({ error: "venueName required" }, { status: 400 });

  const wantsNew = !body.tripId || body.tripId === "new";
  let trip;

  if (wantsNew) {
    const limitError = await checkTripSaveLimit(userId);
    if (limitError) {
      return Response.json({ error: limitError, code: "TRIP_LIMIT" }, { status: 403 });
    }
    const location = body.city
      ? [body.city, body.country].filter(Boolean).join(", ")
      : venue;
    trip = await prisma.tripDraft.create({
      data: {
        userId,
        title: `Saved from share — ${location}`,
        location,
        itinerary: initialItinerary(venue, body),
        itineraryUpdatedAt: new Date(),
        members: { create: { userId, role: "owner" } },
      },
    });
  } else {
    const existing = await prisma.tripDraft.findFirst({
      where: {
        id: body.tripId,
        OR: [{ userId }, { members: { some: { userId } } }],
      },
    });
    if (!existing) return Response.json({ error: "Trip not found" }, { status: 404 });

    trip = await prisma.tripDraft.update({
      where: { id: existing.id },
      data: {
        itinerary: appendToItinerary(existing.itinerary ?? "", venue, body),
        itineraryUpdatedAt: new Date(),
      },
    });
  }

  // Mirror the shared place into SavedPlace so /saves + /api/geofence/register
  // can query it without parsing itinerary markdown. Fire-and-forget on
  // failure — a bad structured write shouldn't 500 the share flow after the
  // itinerary already updated.
  try {
    await prisma.savedPlace.create({
      data: {
        userId,
        tripId: trip.id,
        venueName: venue,
        city: body.city ?? null,
        country: body.country ?? null,
        lat: typeof body.lat === "number" ? body.lat : null,
        lon: typeof body.lon === "number" ? body.lon : null,
        placeTypes: body.placeTypes ?? [],
        category: mapCategory(body.placeTypes ?? []),
        thumbnail: body.thumbnail ?? null,
        source: body.source ?? "manual",
        sourceUrl: body.sourceUrl ?? null,
      },
    });
  } catch (e) {
    console.error("add-from-share: SavedPlace mirror failed", e);
  }

  return Response.json({
    trip,
    tripUrl: `/trip/${trip.id}`,
  });
}

// ── Markdown itinerary helpers ─────────────────────────────────────────────
//
// Existing itineraries are plain markdown, generated by /api/chat's AI
// pipeline. Each day looks like:
//
//   ## Day 1 — 2026-08-14
//   - **Morning** Visit Fushimi Inari before sunrise <!--gk:place lat=… lon=…-->
//   - **Lunch** Ramen at ...
//
// We preserve that shape: append a bullet under the target day, with an
// HTML-comment carrying structured metadata (lat/lon/source) so the front-end
// can render a "shared" chip and the AI can respect it on re-generation.

function initialItinerary(venue: string, b: ShareBody): string {
  return [
    `## Saved from share`,
    ``,
    formatBullet(venue, b),
    ``,
  ].join("\n");
}

function appendToItinerary(current: string, venue: string, b: ShareBody): string {
  const bullet = formatBullet(venue, b);
  if (!current.trim()) return initialItinerary(venue, b);

  // Split into day blocks: each starts with "## Day N" (or "## Saved from share").
  const dayHeader = /^## (Day \d+|Saved from share)/gm;
  const headers: Array<{ index: number; text: string }> = [];
  let m: RegExpExecArray | null;
  while ((m = dayHeader.exec(current)) !== null) {
    headers.push({ index: m.index, text: m[0] });
  }
  if (!headers.length) {
    return `${current.trimEnd()}\n\n## Saved from share\n\n${bullet}\n`;
  }
  // Decide which day block to append to.
  const targetIdx = pickDayIndex(headers.length, b.dayIndex);
  const targetHeader = headers[targetIdx];
  const nextHeader = headers[targetIdx + 1];
  const blockEnd = nextHeader ? nextHeader.index : current.length;

  const before = current.slice(0, blockEnd).trimEnd();
  const after = current.slice(blockEnd);
  return `${before}\n${bullet}\n${after ? "\n" + after.trimStart() : ""}`;
}

function pickDayIndex(headerCount: number, requested?: number): number {
  if (!requested || requested < 1) return headerCount - 1;   // last day
  return Math.min(requested - 1, headerCount - 1);
}

function formatBullet(venue: string, b: ShareBody): string {
  const meta: string[] = [];
  if (typeof b.lat === "number") meta.push(`lat=${b.lat}`);
  if (typeof b.lon === "number") meta.push(`lon=${b.lon}`);
  if (b.source) meta.push(`src=${b.source}`);
  if (b.sourceUrl) meta.push(`url=${b.sourceUrl}`);
  const comment = meta.length ? ` <!--gk:place ${meta.join(" ")}-->` : "";
  const cityLine = b.city ? ` — ${b.city}` : "";
  return `- **Saved** ${venue}${cityLine}${comment}`;
}
